mmazzarolo/react-native-modal-datetime-picker

- package.json
- src/index.d.ts
> Added typescript definitions

- src/CustomDatePickerIOS/index.js
> extend dateTimeModa styling for ios

- src/CustomDatePickerAndroid/index.js
> Fix is24Hour param being ignored for 'datetime' scenario

- package.json
References https://github.com/react-native-community/react-native-modal/pull/43
@mmazzarolo You guessed it :P
> Bump react-native-modal

- package.json
- yarn.lock
> upgraded momentjs to 2.19.0

- src/CustomDatePickerAndroid/index.js
Fixing that Android date can be NaN.NaN.NaN in release mode
> fixing that android date becomes NaN in release

- src/CustomDatePickerIOS/index.js
- src/CustomDatePickerIOS/index.style.js
because `SafeViewArea` doesn't work in modal, we must add margin bottom for button.
> add margin bottom for iPhone X

- src/index.d.ts
'locale' props type definition for DatePickerIOS
this resolves #166
> include locale DatePickerIOS prop type definition

- package-lock.json
- package.json
Updated react-native-modal dependency to resolve  [a compatibility issue with RN 0.56](https://github.com/react-native-community/react-native-modal/issues/178)
> Updated react-native-modal to support RN 0.56+

- src/CustomDatePickerAndroid/index.js
fixes #173
Simply removing catch around synchronous code, resulted in unhandled promise rejection, if error in callbacks.
Resulting in kind of cryptic yellow-box error.
So I ended up caching those and now it is proper red-box error if error in callbacks.
Other than that, no functionality change.
> improve error handling for android

- src/CustomDatePickerIOS/index.js
> fix: reset date to initial date

- README.md
> Update npm address and example

- package.json
- yarn.lock
> build: update `react-native-modal@11.0.2`

- src/CustomDatePickerIOS.js
- typings/index.d.ts
While implementing dark mode for our app we needed to change the background color of the cancel button container. So I added a prop to set this.
> Add cancelButtonContainerStyleIOS prop

- example/package.json
- example/yarn.lock
> fix: Fixed the example module name

- README.md
> docs: Fixed README

- README.md
Make the description of `automatic locale in iOS` more kind. The reason is to prevent confusion for users unfamiliar with editing `AppDelegate.m`.
> docs: update README that automatic locale in iOS

- src/DateTimePickerModal.android.js
- src/DateTimePickerModal.ios.js
> Add minimum and maximum dates

- README.md
- typings/index.d.ts
> Removed titleStyle from docs/types

- src/DateTimePickerModal.android.js
- src/DateTimePickerModal.ios.js
- src/index.js
Export custom component styles to make the more composable. See #366
> Export styles

- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- package.json
Updated the example development setup
> chore: Example update

- typings/index.d.ts
> Export prop types for date-time-picker

- src/DateTimePickerModal.js
> fix: unsupported platforms

- README.md
- src/DateTimePickerModal.ios.js
> Removed isDarkModeEnabled prop and formatting

- typings/index.d.ts
> Updated TS definitions

- README.md
> docs: Add minimum/maximum date FAQ

- typings/index.d.ts
Update typings with cancelButtonTestID and confirmButtonTestID
> feat: update typings

- README.md
> docs: Added managed flow required configuration

- typings/index.d.ts
Found a problem when using  "pickerStyleIOS" props. it does not exist in Typing file
no functional changes here
once after build you can use the available props.
> add pickerStyleIOS to Typing file

- typings/index.d.ts
In #697 I forgot to add typescript types - this PR fixes this
N/A
> chore: add missing type declarations

- README.md
Prepend expo install with npx as to use the new expo cli.
> Prepend npx to expo install
