mmazzarolo/react-native-modal-datetime-picker

- README.md
- src/CustomDatePickerIOS/index.js
- src/CustomDatePickerIOS/index.style.js
Hi mmazzarolo,
According to the issue I have posted this morning (https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/3), here is a pull request that should let users do what they want now.
I didn't gave the possibility to show or not the cancel button. If you want to add this feature, that could be nice.
I'm just not sure about the PropTypes.number I set for the awaited Stylesheet objects for te props titleContainerStyleIOS, titleStyleIOS, ... It let you check this.
I also updated the readme.
Let me know if you find any problem.
Thanx for your work !
> Added customizations possibilities

- README.md
- package.json
- src/CustomDatePickerAndroid/index.js
This will allow folks to have the option of showing an AM/PM picker on Android by setting the prop:
``is24Hour={false}``
> Expose is24Hour to props

- src/CustomDatePickerIOS/index.js
when date in the porps gets changed for iOS, local state was not updated.
> state updated when date gets changed for iOS

- package.json
Hi,
i have added the keys [repository](https://docs.npmjs.com/files/package.json#repository) and [homepage](https://docs.npmjs.com/files/package.json#homepage) to the `package.json` file.
These keys are used at various places.
For example, a link to the github page will appear on the [npm package details page](https://www.npmjs.com/package/react-native-modal-datetime-picker).
It is very useful too, if you are using `yarn outdated`. If there is a new version of your package you can directly click on the provided url (the github page). So it is easy to check for new features or breaking changes.
Keep up your good work!
> Improve package.json by adding homepage and repository keys

- src/CustomDatePickerIOS/index.js
TL/DR:
We no longer allow our user to tap the confirm button unless the picker is still.
Long version:
Up until now when the user interacted with the picker, if someone tapped on the confirm button, the state was not yet changed and thus the picked value would be old and miss-leading.
That's a bug of DatePickerIOS but since facebook doesn't do anything about it, I decided to created a workaround.
We no longer allow our user to tap the confirm button unless the picker is still.
They can always tap the cancel button anyway.
> We no longer allow a user to tap the confirm button unless picker = still.

- README.md
- src/CustomDatePickerAndroid/index.js
- src/CustomDatePickerIOS/index.js
- src/index.d.ts
I'm using react-native-modal-datetime-picker in a search where changing the date may make the modified result disappear. Everything worked fine, until I started getting warnings for calling setState on an unmounted component.
It turned out that the animation was still running when I refreshed my search, so when the animation was done the component had already unmounted.
The solution was to wait for the animation using **onHideAfterConfirm**.
It works for me, so I though I'd share it.
> Added onHideAfterConfirm

- src/CustomDatePickerAndroid/index.js
This PR changes the default value of `datePickerModeAndroid` to `'default'`, to prevent an [issue](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/29) related to changing the style of the date and time pickers on Android.
> Change default value of datePickerModeAndroid

- README.md
As `TimePickerAndroid` does not support these options, nor [does Android's native TimePicker](https://developer.android.com/reference/android/widget/TimePicker.html) this is inevitable but should be documented.
> Reflect min & max date support on Android

- src/index.d.ts
I'm not sure why it wasn't like this but typescript needs it to be like this in order to work. Without this change it just gives errors.
> Fix TypeScript typings

- src/CustomDatePickerAndroid/index.js
Fixes #71.
This is a starting point for discussion, since the solution is somewhat brute force at the moment by simply repulling time or date from props for _showDatePickerAndroid and _showTimePickerAndroid respectively.
At least on my code, this fixes the resetting issue.
> Fix Android Resetting Date or Time

- README.md
- src/CustomDatePickerIOS/index.js
- src/index.d.ts
add a new prop -- neverDisableConfirmIOS -- that prevents disabling the confirm button on ios picker wheel
see #82
> add a new prop: neverDisableConfirmIOS

- README.md
I ran into this issue when building a react native app. 
I had an input field for a start date and end date on the same page but only used one function to show and hide both. This caused problems where sometimes the start date would show up in the end date input while other times it wouldn't. 
Just thought about adding it to the FAQ in case others run into this issue!
> Add FAQ question and answer for handling multiple datetime pickers

- src/CustomDatePickerAndroid/index.js
- src/CustomDatePickerIOS/index.js
This pull request is to replace React.Component with React.PureComponent to avoid unnecessary re-renders as per the suggestion on ReactJS performance optimization docs. (https://reactjs.org/docs/optimizing-performance.html)
> Replacing React.Component with React.PureComponent

- src/CustomDatePickerAndroid/index.js
Handle props on componentDidMount() to allow displaying the picker on component mount.
> Allow displaying the picker on mount (Android)

- README.md
- src/CustomDatePickerIOS/index.js
- src/index.d.ts
Need this to be able to replace DatePickerIOS w/ something like dgladkov/react-native-uncontrolled-date-picker-ios
Usage:
```javascript
<TimerPicker
pickerRefCb={(datePicker) => { this.datepickerRef = datePicker; }}
customDatePickerIOS={Platform.OS === 'ios' ? UncontrolledDatePickerIOS : null}
onConfirm={() => {
if (this.datepickerRef && this.datepickerRef.getDate) {
this.datepickerRef.getDate((datePicked) => {
// do something with the datePicked Date obj
});
}
}}
/>
```
> We can now use a custom DatePicker component

- src/CustomDatePickerAndroid/index.js
Currently, the `datePickerModeAndroid` prop is only apply to `DatePickerAndroid` not the `TimePickerAndroid`. This PR make it apply to `TimePickerAndroid` too. So, when user set`mode` as  `time` or `datetime` the `TimePickerAndroid` will display correctly and consistently with `DatePickerAndroid`.
> Apply datePickerModeAndroid prop to TimePickerAndroid.

- package.json
- src/CustomDatePickerAndroid/index.js
Moment.js was used to build new Date objects even though we could use native Date object directly. Saves around 51 kB in the final JS bundle when building the React Native app.
Closes #125
> Remove moment dependency

- README.md
Fixed syntax error in `Why is the selected start date being shown in the input field of the end date?`
> Fixed syntax error in example

- src/CustomDatePickerIOS/index.js
This PR aims to fix the issue #161 
- By resetting the localState of date to new Date() on confirmation or cancelation of the modal window solves the issue
> Fixes issue #161 - Differing behavior between iOS and Android 

- .gitignore
- src/CustomDatePickerIOS/index.js
while initializing the state for minuteInterval, Use the values passed from props, if undefined then use '1' as a fallback 
This fixes issue https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/158
> Fix - minuteInterval should take value from props

- README.md
Hi @mmazzarolo 
Thank you for this library, Pretty handy 👍
I needed Datepicker to adapt on current locale. 24h format was not enough. 
So I add a tip in your README for those who like me may need Datepicker to adapt depending user locale.
Thank you
> add README tip for setting locale in iOS

- README.md
- src/CustomDatePickerIOS/index.js
- src/index.d.ts
This optional boolean prop, when set to true, will cause the modal's
title container to not render.
> Add hideTitleContainerIOS prop

- src/index.d.ts
I feel like the titleStyle, confirmTextStyle, and cancelTextStyle props should be of type TextStyle instead of ViewStyle.
> Change text and title style definitions to TextStyle

- README.md
- src/CustomDatePickerAndroid/index.js
- src/index.d.ts
Allow the user to control DatePickerAndroid.mode and TimePickerAndroid.mode independently as currently some values for datePickerModeAndroid (e.g. 'calendar') will cause the component to throw errors as the value is passed to both DatePickerAndroid.open() and TimePickerAndroid.open().
> Add timePickerModeAndroid prop

- src/CustomDatePickerIOS.js
Attempt to resolve this issue: https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/247
As it is, the comparison on componentWillUpdate will always return true for derived data, even if the dates are the same, because the object will be different.
Run the example from referenced issue
> comparing dates by value instead of objects

- src/CustomDatePickerIOS.js
Fixed the `reactNativeModalPropsIOS` prop behaviour (a bug was introduced in a previous PR that made the `reactNativeModalPropsIOS` prop not behave correctly)
> fix "reactNativeModalPropsIOS" prop behaviour

- README.md
- src/CustomDatePickerIOS.js
- typings/index.d.ts
Add iOS 13 dark-mode support
See the updated README for the setup instructions. 
Fixes issue #283 
Related PRs: #286 #284
> feat: Add iOS 13 dark-mode support

- src/DateTimePickerModal.ios.js
`onHideAfterConfirm` callback was recently renamed to `onHide` in [v8.0.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/301). After simple props renaming in my project I found that `onHide` doesn't work anymore.
In `src/DateTimePickerModal.ios.js:178` I found that `onModalHide` Modal prop is used, but there isn't such a props in `src/Modal.js` component actually. Obviously, it was renamed to `onHide`. But this change wasn't propagated to `src/DateTimePickerModal.ios.js`.
This simple PR fixes the issue.
> fix: `onHide` callback doesn't work on iOS

- typings/index.d.ts
This will allow to properly pass typings from custom components
Tested locally by trying to use DateTimePickerProps in code.
> Allow to access props interface from outside

- typings/index.d.ts
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/301#issuecomment-569931399
Installed to a local project, verified that types are correct.
One issue is that `IOSNativeProps` from @react-native-community/react-native-datetimepicker is typed as any, probably because it is not specified as a dependency/devDependency, only as a peerDependency
> feat: Added custom component types

- src/DateTimePickerModal.ios.js
Small fix for broken prop: https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/301#issuecomment-572325253
> fix: Fix hiding header on IOS not working

- src/CustomDatePickerIOS.js
Removes the white background flash when pressing Confirm or Cancel buttons when isDarkModeEnabled is true
1. render
```
<DateTimePicker
isVisible={this.state.isStartDateTimePickerVisible}
onConfirm={this.handleStartDatePicked}
onCancel={this.hideStartDateTimePicker}
mode="datetime"
isDarkModeEnabled={true}
/>
```
2. observe that when clicking Confirm/Cancel the white background flash is not there.
Cheers.
> base underlayColor off of isDarkModeEnabled

- README.md
It would probably makes things easier for people migrating from version 7. At first I copy and pasted the line without thinking about it and expected it to take care of everything, including bumping the version.
> Set the library version to 8.x.x for Expo setup

- typings/index.d.ts
testID is already handling by the props spread into the underlying component, this just adds it to type info
N/A
> Add testID to DateTimePickerProps

- typings/index.d.ts
Some props were imported from an existent @react-native-community/react-native-datetimepicker
package.
Well, `npx tsc` would be sufficient.
> fix: wrong import in typescript typings

- src/DateTimePickerModal.ios.js
Since we can't precisely know when/if the user started spinning the component (on IOS) to pick a date, we can't disable the "Confirm" button without bugs popping up continuously.
This PR removes the logic that disables the "Confirm" button until the component has stopped spinning.
> Remove disable confirm

- typings/index.d.ts
Fixes https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/371
Install the package on a typescript project and verify that typescript doesn't complain on Props that belong to @react-native-community/datetimepicker
On a side note:
This fix includes the Typescript Omit type to filter out the required `value` parameters of the original props.
If you have a minimum version of Typescript specified somewhere that needs to be bumped to > 3.5
> Update Typings to include @react-native-community/datetimepicker props

- src/Modal.js
Use width and height returned from "didUpdateDimensions" listener, instead of multiplying it by 2 which is not needed, and sometimes makes buttons unclickable.
> [BUGFIX] "Confirm" and "Cancel" buttons should be clickable

- typings/index.d.ts
Also added @typescript-eslint/parser and typescript as devDependencies.
This was necessary because the pre-commit hook was preventing me from
committing because these packages were missing. 
**I don't have eslint experience so this should be reviewed**
PR #374 unintentionally broke the `mode` prop.  `DateTimePickerProps` defines the `mode` prop as `'date' | 'time' | 'datetime' | undefined`, as does `IOSNativeProps` from `@react-native-community/datetimepicker`. However, `AndroidNativeProps` defines `mode` as `'date' | 'time' | undefined`.  As a result, the intersection type `DateTimePickerProps & IOSNativeProps & AndroidNativeProps` expects `mode` to be `'date' | 'time' | undefined`, i.e. `'datetime'` is not allowed.
1. Download my minimal repro: …
> fix: typescript types did not allow mode='datetime'

- src/Modal.js
Fixes #379 
As per [documentation](https://reactnative.dev/docs/dimensions) the dimentions should be obtained from the `window` item.
> fix: Use the correct width/height on rotation

- src/Modal.js
Fixes #402
Users are getting a warn about setting "useNativeDriver" to true or false, so we explicitly set it to false in the modal.
Also, minor cleanup.
> fix: Explicitly set "useNativeDriver" to false

- README.md
- example/ios/Podfile.lock
- src/DateTimePickerModal.ios.js
- src/Modal.js
- typings/index.d.ts
Added a new prop: `modalPropsIOS`. It can be used to pass additional props to the [modal](https://reactnative.dev/docs/modal) component used by the iOS picker.
> feat: Added "modalPropsIOS"

- package.json
- src/DateTimePickerModal.ios.js
Removed the following deprecated props:
- `titleIOS`
- `customTitleContainerIOS`
- `onHideAfterConfirm`
- `customDatePickerIOS`
> major: Removed deprecated props

- src/DateTimePickerModal.js
Added a platform-agnostic entry point (except for Android/iOS) that will show a warning for unsupported platforms (instead of making them crash).
> feat: Avoid crashing on unsopported platforms

- src/DateTimePickerModal.android.js
fixes #451, This PR memos the component to avoid triggering a re-render of the upstream library @react-native-community/datetimepicker which recreates the date picker on each render call. I have also converted to hooks while working out how to resolve this issue.
> (fix)(refactor) Memo'd component to avoid re-rendering upstream which has a bug

- src/DateTimePickerModal.ios.js
This removes the manual dark mode toggle in favour of `Appearance.getColorScheme()`. Fixes #458
Add the component,
- Render with light mode (make sure text in spinner is visible)
- Switch to dark mode (on sim this is settings -> dev -> dark appearance.
- Render again and make sure you can still see the text.
> Use dark mode internally rather than passing it in

- src/DateTimePickerModal.android.js
Store current date in a ref instead of state to avoid re-rendering of the time picker. Solves #451
> fix: Don't re-render in datetime mode

- src/utils.js
Update `isIphoneX` helper according to `react-native-iphone-x-helper`.
Adds iPhone 12 and iPhone 12 mini compatibility.
https://github.com/ptelad/react-native-iphone-x-helper/blob/master/index.js#L3-L13
> update isIphoneX helper

- README.md
Based on [the issue](https://github.com/react-native-datetimepicker/datetimepicker/issues/54) and the discussion, some approaches can be used. The most common approach is described at README with this PR.
No Test needed! Just Docs update :smile:
> Docs: Add Section with Solution for "double picker opening" bug

- src/DateTimePickerModal.android.js
Comparing two dates is not possible using the `===` operator. When you would like to check the equality of two dates, you need to use the `getTime()` method. Our component was still re-rendering before comparing dates with `getTime()`.
Object equality isn't tested by the internal value of the object, but by identity. In other words, if it isn't the exact same copy of the Date object, it isn't considered equal.
Here we compare the return values of getTime. The getTime method returns an integer representing the number of milliseconds since midnight of January 1, 1970 (the beginning of the Unix epoch).
> Memoized equal check should check a date's milliseconds

- src/DateTimePickerModal.ios.js
When dark mode is on, the `ConfirmButton` top border remains with a light color.
The PR changes it to have a darker color:
(it seems transparent in the picture - however on device it looks great 🌚)
> Added dark theme option to confirm button

- example/App.js
Let's update the example so that fellow developers do not have to spend time finding out why the Android popup is "shown twice".
It is just example adjustment according to well known workaround :)
> Fix Android popup shown twice bug in example

- src/DateTimePickerModal.ios.js
Changed "Pick a date" to be "Pick a time" when mode is set to time (and no manual value is specified).
> fix: Change default header text for time on iOS

- src/DateTimePickerModal.ios.js
The header text is always "Pick a time" on iOS after #560 merged.
> Fix: header text bug on iOS

- package.json
- src/Modal.js
With ReactNative 0.65.0 the removeListener was deprecated in favor of `remove()`
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#deprecated
> removeListener deprecated in favor of remove()

- typings/index.d.ts
Update minuteInterval type
While using this library, I had the following TypeScript error:
```
No overload matches this call.
Overload 1 of 2, '(props: ReactNativeModalDateTimePickerProps | Readonly<ReactNativeModalDateTimePickerProps>): DateTimePicker', gave the following error.
Type '{ cancelButtonTestID?: string | undefined; confirmButtonTestID?: string | undefined; cancelTextIOS?: string | undefined; confirmTextIOS?: string | undefined; customCancelButtonIOS?: CancelButtonComponent | undefined; ... 21 more ...; onConfirm: (d: Date) => void; }' is not assignable to type 'Readonly<ReactNativeModalDateTimePickerProps>'.
Types of property 'minuteInterval' are incompatible.
Type 'number | undefined' is not assignable to type '2 | 1 | 3 | 4 | 5 | 6 | 10 | 12 | 15 | 20 | 30 | undefined'. …
```
> Fix TypeScript error

- README.md
- src/DateTimePickerModal.ios.js
- typings/index.d.ts
I added a way to change the font color of the buttons, up to now you were only able to change the other colors in the calendar itself.
I implemented the component in my own code and tried it out.
> Added ability to change button font color

- src/DateTimePickerModal.ios.js
- typings/index.d.ts
Fix for https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/567
Pulls in changes from https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/585, along with the requested changes in that PR
Followed @mmazzarolo's suggestion in other PR to create a new project, add date picker, and add changes to `index.d.ts`
some screen shots below:
display options available
inline display option used, no ts error
> fix: display prop typscript issue

- typings/index.d.ts
Thank you guys for an amazing lib!!
**PS:** I am re-creating this PR because the I did not have the right email set in my commit, so the commit signature was unverified. Sorry for that!
The library is missing the `CancelButton` and `ConfirmButton` components for the iOS only properties `customCancelButtonIOS` and `customConfirmButtonIOS`. I also found a good idea to export their styles, just in case someone (myself included) wants to do some slight changes.
All I mentioned works fine, but whenever you try to import any of these two components or their styles you get some red on your code editor. That's because the declaration file is missing these elements. So all I did was I exported from  `ìndex.d.ts` the `CancelButton` and `ConfirmButton` components, told the declaration file the …
> Adding customCancelButton and customConfirmButton types

- typings/index.d.ts
The prop onChange was being interpreted as an union between the onChange prop of this library and the onChange prop of `@react-native-community/datetimepicker`. I ommited this key because Typescript was expecting a callback with two params (event, date) instead of just one as this library says it should receive (only date).
> fix: omitted underlying onChange prop type

- README.md
- package.json
- src/DateTimePickerModal.ios.js
Continuing on from our discussion #672, the aim of this PR is to provide a temporary resolution of the occasional styling bug with inline display in datetime mode on iOS. More context is in the linked issue. When testing, I found that 370 is the most appropriate value with the current default styles of the picker. However, after more tinkering, I discovered that applying various other styles to the picker, e.g. `modalStyleIOS` and `pickerStyleIOS`, it could affect the efficiency of this "fix". With that said, this will work IF the users use the default styles provided by this library. For cases when they provide more of their own styles, a `pickerComponentStyleIOS` prop is now exposed which they can use to overwrite the fix applied in this PR. I'm not sure if this is the best approach, …
> fix: resolve occasional styling bug with inline display in datetime mode on iOS

- typings/index.d.ts
As discussed in #709 onCancel does not have any parameters. This pull request corrects the typings to reflect this
Compiles successfully
> fix: Remove date parameter from onCancel

- src/DateTimePickerModal.ios.js
Swap the button style on iOS as suggested on #689 
The order of style on cancel button is the same as confirm button.
> fix: swap ios button style, closes #689

- src/DateTimePickerModal.ios.js
- src/utils.js
- Added missing iPhone 14 Pro & iPhone 14 Pro Max dimensions to the `isIphoneX()` method.
- The `marginBottom` is applied to `modal` styles rather than the cancel button styles. This allows overriding the bottom margin through `modalStyleIOS`.
- The margin value is updated to `34pt` which is the proper size of the iOS bottom inset. Reference: [iPhone 14 Screen Sizes](https://useyourloaf.com/blog/iphone-14-screen-sizes/)
The bottom inset of 34pt should appear for iPhone 14 Pro and iPhone 14 Pro Max. Users should be able to manually update the inset value through `modalStyleIOS` prop.
> Support iPhone 14 Pro & Pro Max safe area bottom inset
